// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: transactions/transactions.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_DEBIT    TransactionType = 0
	TransactionType_CREDIT   TransactionType = 1
	TransactionType_TRANSFER TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "DEBIT",
		1: "CREDIT",
		2: "TRANSFER",
	}
	TransactionType_value = map[string]int32{
		"DEBIT":    0,
		"CREDIT":   1,
		"TRANSFER": 2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{0}
}

// The Event: Transaction Service -> Transaction Orchestrator
type TransactionState int32

const (
	TransactionState_TRAN_INITIATED  TransactionState = 0
	TransactionState_TRAN_PROCESSING TransactionState = 1
	TransactionState_TRAN_COMPLETED  TransactionState = 2
	TransactionState_TRAN_REJECTED   TransactionState = 3
	TransactionState_TRAN_CANCELLED  TransactionState = 4
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRAN_INITIATED",
		1: "TRAN_PROCESSING",
		2: "TRAN_COMPLETED",
		3: "TRAN_REJECTED",
		4: "TRAN_CANCELLED",
	}
	TransactionState_value = map[string]int32{
		"TRAN_INITIATED":  0,
		"TRAN_PROCESSING": 1,
		"TRAN_COMPLETED":  2,
		"TRAN_REJECTED":   3,
		"TRAN_CANCELLED":  4,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_transactions_transactions_proto_enumTypes[1].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_transactions_transactions_proto_enumTypes[1]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{1}
}

// The Command: Transaction Orchestrator -> Transaction Service
type CreateTransactionCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SagaId           string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TransactionType  TransactionType        `protobuf:"varint,4,opt,name=transaction_type,json=transactionType,proto3,enum=transactions.TransactionType" json:"transaction_type,omitempty"`
	TransactionState string                 `protobuf:"bytes,5,opt,name=transaction_state,json=transactionState,proto3" json:"transaction_state,omitempty"`
	Description      string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CustomerId       string                 `protobuf:"bytes,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTransactionCommand) Reset() {
	*x = CreateTransactionCommand{}
	mi := &file_transactions_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionCommand) ProtoMessage() {}

func (x *CreateTransactionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionCommand.ProtoReflect.Descriptor instead.
func (*CreateTransactionCommand) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionCommand) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CreateTransactionCommand) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CreateTransactionCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateTransactionCommand) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_DEBIT
}

func (x *CreateTransactionCommand) GetTransactionState() string {
	if x != nil {
		return x.TransactionState
	}
	return ""
}

func (x *CreateTransactionCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type TransactionCreatedEvent struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SagaId                   string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	SourceAccountNumber      string                 `protobuf:"bytes,2,opt,name=source_account_number,json=sourceAccountNumber,proto3" json:"source_account_number,omitempty"`
	DestinationAccountNumber string                 `protobuf:"bytes,3,opt,name=destination_account_number,json=destinationAccountNumber,proto3" json:"destination_account_number,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,4,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	TransactionType          TransactionType        `protobuf:"varint,5,opt,name=transaction_type,json=transactionType,proto3,enum=transactions.TransactionType" json:"transaction_type,omitempty"`
	TransactionState         TransactionState       `protobuf:"varint,6,opt,name=transactionState,proto3,enum=transactions.TransactionState" json:"transactionState,omitempty"`
	Amount                   string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Description              string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CustomerId               string                 `protobuf:"bytes,9,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TransactionCreatedEvent) Reset() {
	*x = TransactionCreatedEvent{}
	mi := &file_transactions_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCreatedEvent) ProtoMessage() {}

func (x *TransactionCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCreatedEvent.ProtoReflect.Descriptor instead.
func (*TransactionCreatedEvent) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionCreatedEvent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *TransactionCreatedEvent) GetSourceAccountNumber() string {
	if x != nil {
		return x.SourceAccountNumber
	}
	return ""
}

func (x *TransactionCreatedEvent) GetDestinationAccountNumber() string {
	if x != nil {
		return x.DestinationAccountNumber
	}
	return ""
}

func (x *TransactionCreatedEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TransactionCreatedEvent) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_DEBIT
}

func (x *TransactionCreatedEvent) GetTransactionState() TransactionState {
	if x != nil {
		return x.TransactionState
	}
	return TransactionState_TRAN_INITIATED
}

func (x *TransactionCreatedEvent) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionCreatedEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type TransactionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SourceAccountNumber      string                 `protobuf:"bytes,1,opt,name=source_account_number,json=sourceAccountNumber,proto3" json:"source_account_number,omitempty"`
	DestinationAccountNumber string                 `protobuf:"bytes,2,opt,name=destination_account_number,json=destinationAccountNumber,proto3" json:"destination_account_number,omitempty"`
	TransactionType          TransactionType        `protobuf:"varint,3,opt,name=transaction_type,json=transactionType,proto3,enum=transactions.TransactionType" json:"transaction_type,omitempty"`
	Amount                   string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description              string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CustomerId               string                 `protobuf:"bytes,6,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_transactions_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionRequest) GetSourceAccountNumber() string {
	if x != nil {
		return x.SourceAccountNumber
	}
	return ""
}

func (x *TransactionRequest) GetDestinationAccountNumber() string {
	if x != nil {
		return x.DestinationAccountNumber
	}
	return ""
}

func (x *TransactionRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_DEBIT
}

func (x *TransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type TransferCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SagaId                   string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	CorrelationId            string                 `protobuf:"bytes,2,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	SourceAccountNumber      string                 `protobuf:"bytes,3,opt,name=source_account_number,json=sourceAccountNumber,proto3" json:"source_account_number,omitempty"`
	DestinationAccountNumber string                 `protobuf:"bytes,4,opt,name=destination_account_number,json=destinationAccountNumber,proto3" json:"destination_account_number,omitempty"`
	Amount                   string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Description              string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CustomerId               string                 `protobuf:"bytes,7,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TransferCommand) Reset() {
	*x = TransferCommand{}
	mi := &file_transactions_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCommand) ProtoMessage() {}

func (x *TransferCommand) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCommand.ProtoReflect.Descriptor instead.
func (*TransferCommand) Descriptor() ([]byte, []int) {
	return file_transactions_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *TransferCommand) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *TransferCommand) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TransferCommand) GetSourceAccountNumber() string {
	if x != nil {
		return x.SourceAccountNumber
	}
	return ""
}

func (x *TransferCommand) GetDestinationAccountNumber() string {
	if x != nil {
		return x.DestinationAccountNumber
	}
	return ""
}

func (x *TransferCommand) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferCommand) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_transactions_transactions_proto protoreflect.FileDescriptor

const file_transactions_transactions_proto_rawDesc = "" +
	"\n" +
	"\x1ftransactions/transactions.proto\x12\ftransactions\"\xbb\x02\n" +
	"\x18CreateTransactionCommand\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12H\n" +
	"\x10transaction_type\x18\x04 \x01(\x0e2\x1d.transactions.TransactionTypeR\x0ftransactionType\x12+\n" +
	"\x11transaction_state\x18\x05 \x01(\tR\x10transactionState\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcustomer_id\x18\a \x01(\tR\n" +
	"customerId\"\xbb\x03\n" +
	"\x17TransactionCreatedEvent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x122\n" +
	"\x15source_account_number\x18\x02 \x01(\tR\x13sourceAccountNumber\x12<\n" +
	"\x1adestination_account_number\x18\x03 \x01(\tR\x18destinationAccountNumber\x12$\n" +
	"\rcorrelationId\x18\x04 \x01(\tR\rcorrelationId\x12H\n" +
	"\x10transaction_type\x18\x05 \x01(\x0e2\x1d.transactions.TransactionTypeR\x0ftransactionType\x12J\n" +
	"\x10transactionState\x18\x06 \x01(\x0e2\x1e.transactions.TransactionStateR\x10transactionState\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1f\n" +
	"\vcustomer_id\x18\t \x01(\tR\n" +
	"customerId\"\xab\x02\n" +
	"\x12TransactionRequest\x122\n" +
	"\x15source_account_number\x18\x01 \x01(\tR\x13sourceAccountNumber\x12<\n" +
	"\x1adestination_account_number\x18\x02 \x01(\tR\x18destinationAccountNumber\x12H\n" +
	"\x10transaction_type\x18\x03 \x01(\x0e2\x1d.transactions.TransactionTypeR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcustomer_id\x18\x06 \x01(\tR\n" +
	"customerId\"\x9d\x02\n" +
	"\x0fTransferCommand\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12$\n" +
	"\rcorrelationId\x18\x02 \x01(\tR\rcorrelationId\x122\n" +
	"\x15source_account_number\x18\x03 \x01(\tR\x13sourceAccountNumber\x12<\n" +
	"\x1adestination_account_number\x18\x04 \x01(\tR\x18destinationAccountNumber\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcustomer_id\x18\a \x01(\tR\n" +
	"customerId*6\n" +
	"\x0fTransactionType\x12\t\n" +
	"\x05DEBIT\x10\x00\x12\n" +
	"\n" +
	"\x06CREDIT\x10\x01\x12\f\n" +
	"\bTRANSFER\x10\x02*v\n" +
	"\x10TransactionState\x12\x12\n" +
	"\x0eTRAN_INITIATED\x10\x00\x12\x13\n" +
	"\x0fTRAN_PROCESSING\x10\x01\x12\x12\n" +
	"\x0eTRAN_COMPLETED\x10\x02\x12\x11\n" +
	"\rTRAN_REJECTED\x10\x03\x12\x12\n" +
	"\x0eTRAN_CANCELLED\x10\x04B.\n" +
	"\x16com.demobanking.eventsZ\x14internal/model;modelb\x06proto3"

var (
	file_transactions_transactions_proto_rawDescOnce sync.Once
	file_transactions_transactions_proto_rawDescData []byte
)

func file_transactions_transactions_proto_rawDescGZIP() []byte {
	file_transactions_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_transactions_proto_rawDesc), len(file_transactions_transactions_proto_rawDesc)))
	})
	return file_transactions_transactions_proto_rawDescData
}

var file_transactions_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transactions_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transactions_transactions_proto_goTypes = []any{
	(TransactionType)(0),             // 0: transactions.TransactionType
	(TransactionState)(0),            // 1: transactions.TransactionState
	(*CreateTransactionCommand)(nil), // 2: transactions.CreateTransactionCommand
	(*TransactionCreatedEvent)(nil),  // 3: transactions.TransactionCreatedEvent
	(*TransactionRequest)(nil),       // 4: transactions.TransactionRequest
	(*TransferCommand)(nil),          // 5: transactions.TransferCommand
}
var file_transactions_transactions_proto_depIdxs = []int32{
	0, // 0: transactions.CreateTransactionCommand.transaction_type:type_name -> transactions.TransactionType
	0, // 1: transactions.TransactionCreatedEvent.transaction_type:type_name -> transactions.TransactionType
	1, // 2: transactions.TransactionCreatedEvent.transactionState:type_name -> transactions.TransactionState
	0, // 3: transactions.TransactionRequest.transaction_type:type_name -> transactions.TransactionType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transactions_transactions_proto_init() }
func file_transactions_transactions_proto_init() {
	if File_transactions_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_transactions_proto_rawDesc), len(file_transactions_transactions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transactions_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_transactions_proto_depIdxs,
		EnumInfos:         file_transactions_transactions_proto_enumTypes,
		MessageInfos:      file_transactions_transactions_proto_msgTypes,
	}.Build()
	File_transactions_transactions_proto = out.File
	file_transactions_transactions_proto_goTypes = nil
	file_transactions_transactions_proto_depIdxs = nil
}
