// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/users.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureReason int32

const (
	FailureReason_USER_NOT_FOUND      FailureReason = 0
	FailureReason_USER_ALREADY_EXISTS FailureReason = 1
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "USER_ALREADY_EXISTS",
	}
	FailureReason_value = map[string]int32{
		"USER_NOT_FOUND":      0,
		"USER_ALREADY_EXISTS": 1,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_users_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_proto_users_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{0}
}

// The Command: Account Orchestrator -> User Service
type ValidateUserCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserCommand) Reset() {
	*x = ValidateUserCommand{}
	mi := &file_proto_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserCommand) ProtoMessage() {}

func (x *ValidateUserCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserCommand.ProtoReflect.Descriptor instead.
func (*ValidateUserCommand) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateUserCommand) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *ValidateUserCommand) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// The Event: User Service -> Account Orchestrator
type UserValidatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Validated     bool                   `protobuf:"varint,3,opt,name=validated,proto3" json:"validated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserValidatedEvent) Reset() {
	*x = UserValidatedEvent{}
	mi := &file_proto_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserValidatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserValidatedEvent) ProtoMessage() {}

func (x *UserValidatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserValidatedEvent.ProtoReflect.Descriptor instead.
func (*UserValidatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserValidatedEvent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *UserValidatedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserValidatedEvent) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

type UserNotValidatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Validated     bool                   `protobuf:"varint,3,opt,name=validated,proto3" json:"validated,omitempty"`
	FailureReason FailureReason          `protobuf:"varint,4,opt,name=failureReason,proto3,enum=users.FailureReason" json:"failureReason,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNotValidatedEvent) Reset() {
	*x = UserNotValidatedEvent{}
	mi := &file_proto_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotValidatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotValidatedEvent) ProtoMessage() {}

func (x *UserNotValidatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotValidatedEvent.ProtoReflect.Descriptor instead.
func (*UserNotValidatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{2}
}

func (x *UserNotValidatedEvent) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *UserNotValidatedEvent) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserNotValidatedEvent) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *UserNotValidatedEvent) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_USER_NOT_FOUND
}

func (x *UserNotValidatedEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_users_proto protoreflect.FileDescriptor

const file_proto_users_proto_rawDesc = "" +
	"\n" +
	"\x11proto/users.proto\x12\x05users\"G\n" +
	"\x13ValidateUserCommand\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"d\n" +
	"\x12UserValidatedEvent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tvalidated\x18\x03 \x01(\bR\tvalidated\"\xbd\x01\n" +
	"\x15UserNotValidatedEvent\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tvalidated\x18\x03 \x01(\bR\tvalidated\x12:\n" +
	"\rfailureReason\x18\x04 \x01(\x0e2\x14.users.FailureReasonR\rfailureReason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*<\n" +
	"\rFailureReason\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x12\x17\n" +
	"\x13USER_ALREADY_EXISTS\x10\x01B(\n" +
	"\x16com.demobanking.eventsZ\x0einternal/modelb\x06proto3"

var (
	file_proto_users_proto_rawDescOnce sync.Once
	file_proto_users_proto_rawDescData []byte
)

func file_proto_users_proto_rawDescGZIP() []byte {
	file_proto_users_proto_rawDescOnce.Do(func() {
		file_proto_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_users_proto_rawDesc), len(file_proto_users_proto_rawDesc)))
	})
	return file_proto_users_proto_rawDescData
}

var file_proto_users_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_users_proto_goTypes = []any{
	(FailureReason)(0),            // 0: users.FailureReason
	(*ValidateUserCommand)(nil),   // 1: users.ValidateUserCommand
	(*UserValidatedEvent)(nil),    // 2: users.UserValidatedEvent
	(*UserNotValidatedEvent)(nil), // 3: users.UserNotValidatedEvent
}
var file_proto_users_proto_depIdxs = []int32{
	0, // 0: users.UserNotValidatedEvent.failureReason:type_name -> users.FailureReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_users_proto_init() }
func file_proto_users_proto_init() {
	if File_proto_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_users_proto_rawDesc), len(file_proto_users_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_users_proto_goTypes,
		DependencyIndexes: file_proto_users_proto_depIdxs,
		EnumInfos:         file_proto_users_proto_enumTypes,
		MessageInfos:      file_proto_users_proto_msgTypes,
	}.Build()
	File_proto_users_proto = out.File
	file_proto_users_proto_goTypes = nil
	file_proto_users_proto_depIdxs = nil
}
